--------------------------------------------------------
--  DDL for Trigger SFM_PROCESSING_JOBS_INSERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SFM_PROCESSING_JOBS_INSERT" 
AFTER UPDATE OF QC ON SFM_METADATA
FOR EACH ROW
 WHEN (NEW.QC IS NOT NULL AND OLD.QC IS NULL) BEGIN
  INSERT INTO SFM_PROCESSING_JOBS (SFMMETAID, PROJECT_PATH, CREATED_AT)
  VALUES (:NEW.SFMMETAID, :NEW.FILEPATH, SYSDATE);
END;
ALTER TRIGGER "SFM_PROCESSING_JOBS_INSERT" ENABLE
