--------------------------------------------------------
--  DDL for Trigger SFM_PROCESSING_LOGID_PK
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SFM_PROCESSING_LOGID_PK" 
BEFORE INSERT ON SFM_PROCESSING_LOGS FOR EACH ROW
BEGIN
    IF :NEW.LOG_ID IS NULL THEN
    SELECT SFM_PROCESSING_LOGS_LOGID_SEQ.NEXTVAL INTO :NEW.LOG_ID FROM DUAL;
END IF;
END;
ALTER TRIGGER "SFM_PROCESSING_LOGID_PK" ENABLE
