--------------------------------------------------------
--  DDL for Trigger SFM_PROCESSING_JOBID_PK
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SFM_PROCESSING_JOBID_PK" 
BEFORE INSERT ON SFM_PROCESSING_JOBS FOR EACH ROW
BEGIN
    IF :NEW.JOB_ID IS NULL THEN
    SELECT SFM_PROCESSING_JOBS_JOBID_SEQ.NEXTVAL INTO :NEW.JOB_ID FROM DUAL;
END IF;
END;
ALTER TRIGGER "SFM_PROCESSING_JOBID_PK" ENABLE
