--------------------------------------------------------
--  DDL for Table SFM_PROCESSING_JOBS
--------------------------------------------------------

  CREATE TABLE "SFM_PROCESSING_JOBS" ("JOB_ID" NUMBER, "BATCH_ID" NUMBER, "SFMMETAID" NUMBER, "PROJECT_PATH" VARCHAR2(20), "START_STEP" NUMBER, "END_STEP" NUMBER, "QUALITY" NUMBER, "SURVEY_YEAR" VARCHAR2(20), "PRORITY" NUMBER, "STATUS" VARCHAR2(20), "ERROR_MESSAGE" VARCHAR2(20), "CREATED_AT" TIMESTAMP (6), "UPDATED_AT" TIMESTAMP (6), "STARTED_AT" TIMESTAMP (6), "COMPLETED_AT" TIMESTAMP (6))
