--------------------------------------------------------
--  DDL for Sequence SFM_PROCESSING_LOGS_LOGID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SFM_PROCESSING_LOGS_LOGID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL
