--------------------------------------------------------
--  DDL for View V_SFM_PROCESSING
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "V_SFM_PROCESSING" ("LOGID", "SITE", "SFMMETAID", "CODE", "START_STEP", "END_STEP", "QUALITY", "LOG_NOTES", "MARKER_0M_NUMBERS", "MARKER_5M_NUMBERS", "MARKER_10M_NUMBERS", "MARKER_15M_NUMBERS", "MARKER_20M_NUMBERS", "FILEPATH", "LAST_MOD_DTM", "LAST_MOD_BY", "CREATE_DTM", "CREATED_BY", "LAST_PROCESSED", "PROCESSING_STATUS", "QC_YN") AS SELECT
    L.LOGID,
    M.SITE,
    L.SFMMETAID,
    L.CODE,
    L.START_STEP,
    L.END_STEP,
    L.QUALITY,
    L.LOG_NOTES,
    M.MARKER_0M_NUMBERS,
    M.MARKER_5M_NUMBERS,
    M.MARKER_10M_NUMBERS,
    M.MARKER_15M_NUMBERS,
    M.MARKER_20M_NUMBERS,
    M.FILEPATH,
    L.LAST_MOD_DTM,
    L.LAST_MOD_BY,
    L.CREATE_DTM,
    L.CREATED_BY,
    L.LAST_PROCESSED,
    L.PROCESSING_STATUS,
    L.QC_YN
  
FROM
  sfm_metadata M
JOIN
  sfm_processing_log L ON M.SFMMETAID = L.SFMMETAID
